### PR TITLE
Update warn-notification.vala

### PR DESCRIPTION
**Pull request by cyberpunkedu**
Add "new line" to warning message.

### CODE REVIEW

**Comment by cyberpunkedu** [comment]
Visually would look better with each sentence on a different line. Uncertain of the syntax.

**Review by cyberpunkedu — COMMENTED** [review]
Added space after \n . Maybe that will fix it?

**Comment by UniversalSuperBox** [comment]
Hmm. @mariogrip, looks like the PR-3 area was cleaned but the Release wasn't updated.

**Comment by UniversalSuperBox** [comment]
With this change:

image

Without this change:

image

It appears that the space needs to be removed, but surprisingly the change works. I didn't expect the newline to be parsed.

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
