### PR TITLE
Fix FTBFS due to tests for indicator-sound

### PR DESCRIPTION
**Pull request by peat-psuwit**
This requires 2 things:
- Make integration-test works under `HOME=/nonexistent` by providing a temporary HOME inside itself.
- Revert the attempt to fix the microphone icon. Turns out the cause isn't that the indicator provides the incorrect icon name, but rather that Unity8 uses the incorrect icon theme (!). As the fix also breaks the test, I decided to just revert it.

This PR comes with Jenkinsfile update. Requires https://github.com/ubports/qtmir/pull/55 to fully fix the microphone icons issue.

For QA: check that the sound indicator is working. If possible, plug a headset with a microphone and see if the microphone slider appears and has correct-looking icon.

### CODE REVIEW

**Review by UniversalSuperBox — APPROVED** [review]
Seems like the indicator works fine after this. Shame the icon is still wrong though.

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

**Comment by peat-psuwit** [comment]
The description is updated. Please take a look.

**Comment by Bolly** [comment]
I used [Recorder](https://open-store.io/app/audio-recorder.luksus) and some headphones with a microphone. Then I listened to the recording.
screenshot20200907_130201651

Checked this on a BQM10FHD running RC 2020 W-36.
It works:
Raising and lowering the volume of the speaker.
Volume up and down of the microphone.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W37

Without plugged anything in jack, sound indicator working.

Plugged headphones with microphone, In the sound indicator appears microphone slider with microphone icon (as in picture from @Bolly above).

Using recording app, the phone microphone instead headset mic was used (maybe app problem). When lowering/raising microphone sensitivity in sound indicator during recording, the volume in recording was lowered/raised correctly (apart from using wrong mic).

When testing making a call with headset+mic, the call used the headset microphone correctly, however using the microphone slider in sound indicator produced no result for the listener.

When plugged headphones without microphone sometimes (in 2 out of 10 cases) the microphone slider appears.

**Comment by Bolly** [comment]
> Using recording app, the phone microphone instead headset mic was used (maybe app problem).

Maybe he won't use the headset microphone either, I didn't take that into account.

Is it necessary to do the test?

**Comment by jezek** [comment]
> Is it necessary to do the test?

I don't know. I just wrote my observations. Maybe this fix was for something else, which works fine now, the observed bugs have nothing to do with this PR and should be filled as new issue. I'll wait what the higher-ups have to say/suggest. ;)

**Pull request merged**
